runtime: nodejs20
service: default
env: standard
instance_class: F1
handlers:
  - url: '.*'
    script: auto
    secure: always
automatic_scaling:
  min_instances: 0
  max_instances: 1
includes:
  - .env_variables.yaml